# general parameters
experiment_name: test_1
dataset_dir: ??? # Must be provided at command line
manual_seed: 123

# What tasks to run, Options
# 1. train - train and run on test set
# 2. eval - run on test set
# 3. visualize - generate visualization output
tasks:
  - train

# Trainer configuration
gpus: 1
accelerator: "ddp"
max_epochs: 384
check_val_every_n_epoch: 20
preload_data: False

# Continue training from specific checkpoint
# set to last.ckpt to use the latest checkpoint
checkpoint:

# whether to run the evaluation on the checkpoint with
# lowest validation loss (otherwise use latest checkpoint)
eval_on_best: True

# defualt parameters
defaults:
  - dataset: scannet
  - model: pointgroup
