# general parameters
task: train
dataset_dir: ??? # Must be provided at command line

# set directory to continue training from (Optional)
continue_from:

# defualt parameters
defaults:
  - dataset: scannet
  - model: pointgroup
