name: S3DIS

classes: 13
ignore_label: -100

train_split: [1, 2, 3, 4, 6]
val_split: [5]
test_split: [5]

input_channel: 3
voxel_size: 0.02
batch_size: 3
max_npoint: 750000
mode: 4 # 4=mean

pretrain:
  frame_skip: 25
  batch_size: 16
  max_steps: 20000
  accumulate_grad_batches: 1

categories:
  [
    "ceiling",
    "floor",
    "wall",
    "beam",
    "column",
    "window",
    "door",
    "table",
    "chair",
    "sofa",
    "bookcase",
    "board",
    "clutter",
  ]

instance_ignore_categories: [
  "wall", 
  "floor", 
  "ceiling"
]
