name: S3DIS

classes: 13
ignore_label: -100

# train_split: [1, 2, 3, 4, 6]
# val_split: [5]
# test_split: [5]

train_split: [1]
val_split: [2]
test_split: [2]

input_channel: 3
scale: 50 # voxel_size = 1 / scale, scale 50(2cm)
batch_size: 3
full_scale: [128, 512]
max_npoint: 250000
mode: 4 # 4=mean

categories:
  [
    "ceiling",
    "floor",
    "wall",
    "beam",
    "column",
    "window",
    "door",
    "table",
    "chair",
    "sofa",
    "bookcase",
    "board",
    "clutter",
  ]
