name: scannetv2
filename_suffix: _inst_nostuff.pth

train_split_file: scannetv2_train.txt
val_split_file: scannetv2_val.txt
test_split_file: scannetv2_test.txt

classes: 20
ignore_label: -100

input_channel: 3
scale: 50 # voxel_size = 1 / scale, scale 50(2cm)
batch_size: 3
full_scale: [128, 512]
max_npoint: 250000
mode: 4 # 4=mean
