name: scannetv2

train_split_file: scannetv2-train.txt
val_split_file: scannetv2-val.txt
test_split_file: scannetv2-test.txt

classes: 20
ignore_label: -100

input_channel: 3
scale: 50 # voxel_size = 1 / scale, scale 50(2cm)
batch_size: 4
max_npoint: 500000
mode: 4 # 4=mean

pretrain:
  frame_skip: 25
  voxel_size: 0.05
  batch_size: 32
  max_epochs: 120
  learning_rate: 0.0001

categories: [
    "wall",
    "floor",
    "cabinet",
    "bed",
    "chair",
    "sofa",
    "table",
    "door",
    "window",
    "bookshelf",
    "picture",
    "counter",
    "desk",
    "curtain",
    "refridgerator", # this is a spelling mistake in the scannet .tsv file
    "shower curtain",
    "toilet",
    "sink",
    "bathtub",
    "otherfurniture",
  ]

instance_ignore_categories: [
  "wall", 
  "floor", 
  "unannotated"
]
