name: scannetv2

train_split_file: scannetv2-train.txt
val_split_file: scannetv2-val.txt
test_split_file: scannetv2-val.txt

classes: 20
ignore_label: -100

input_channel: 3
scale: 50 # voxel_size = 1 / scale, scale 50(2cm)
batch_size: 4
max_npoint: 500000
mode: 4 # 4=mean

pretrain:
  voxel_size: 0.02
  frame_skip: 25
  batch_size: 16
  # max_epochs: 120
  max_steps: 20000
  accumulate_grad_batches: 1

categories: [
    "wall",
    "floor",
    "cabinet",
    "bed",
    "chair",
    "sofa",
    "table",
    "door",
    "window",
    "bookshelf",
    "picture",
    "counter",
    "desk",
    "curtain",
    "refridgerator", # this is a spelling mistake in the scannet .tsv file
    "shower curtain",
    "toilet",
    "sink",
    "bathtub",
    "otherfurniture",
  ]

instance_ignore_categories: ["wall", "floor", "unannotated"]
