name: minkowski

net:
  model: Res16UNet34C
  model_n_out: 32 # Feature dimension
  conv1_kernel_size: 3
  normalize_feature: True
  dist_type: L2
  bn_momentum: 0.05

optimizer:
  type: Adam # Adam or SGD
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-4

scheduler:
  type: 
  exp_gamma: 
  interval:
  frequency:

pretrain:

  optimizer:
    type: SGD # Adam or SGD
    lr: 1e-1
    momentum: 0.9
    weight_decay: 1e-4

  scheduler:
    type: ExpLR
    exp_gamma: 0.99
    interval: "step"
    frequency: 1000

  loss:
    name: "NCELossMoco"
    # name: NCELoss
    args:
      two_domain: True
      LOSS_TYPE: NPID
      OTHER_INPUT: False
      within_format_weight0: 1.0
      within_format_weight1: 0.0
      across_format_weight0: 0.0
      across_format_weight1: 0.0
      NCE_LOSS:
        NORM_EMBEDDING: True
        TEMPERATURE: 0.4
        LOSS_TYPE: cross_entropy
        NUM_NEGATIVES: 4092
        EMBEDDING_DIM: 32
    

train:
  epochs: 384
  train_workers: 8 # data loader workers
  multiplier: 0.5
  prepare_epochs: 10000

test:
  split: val
  test_workers: 4

  eval: True
  save_point_cloud: True
  max_pointcloud_size: 2000000
