name: minkowski

net:
  model: Res16UNet34C
  model_n_out: 32 # Feature dimension
  conv1_kernel_size: 3
  normalize_feature: True
  dist_type: L2
  bn_momentum: 0.05
  loss:

optimizer:
  type: Adam # Adam or SGD
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-4

scheduler:
  type:
  exp_gamma:
  poly_power:
  max_iter:
  interval:
  frequency:

pretrain:
  optimizer:
    type: SGD # Adam or SGD
    lr: 1e-1
    momentum: 0.9
    weight_decay: 1e-4

  scheduler:
    type: ExpLR
    exp_gamma: 0.99
    interval: "step"
    frequency: 1000

  # For moco loss
  loss:
    num_neg_points: 4092 # Number negatives to select
    queue_multiple: 10  # Multiple of batchsize
    temperature: 0.4
    difficulty: hard
    momentum: 0.999

train:
  epochs: 384
  train_workers: 8 # data loader workers
  multiplier: 0.5
  prepare_epochs: 10000

test:
  split: val
  test_workers: 4

  eval: True
  save_point_cloud: True
  max_pointcloud_size: 4000000
