structure:
  model_name: pointgroup
  m: 16 # 16 or 32
  block_residual: True
  block_reps: 2

  use_coords: True

optimizer:
  type: Adam # Adam or SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001

train:
  epochs: 384
  train_workers: 12 # data loader workers

  step_epoch: 384
  multiplier: 0.5

  save_freq: 16 # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

group:
  # point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_epochs: 128

test:
  split: val
  test_epoch: 384
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: True
